const ERROR_CODES = {
  AUTH: {
    UNAUTHORIZED: "UNAUTHORIZED",
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    FORBIDDEN: "FORBIDDEN",
  },
  RESOURCE: {
    NOT_FOUND: "NOT_FOUND",
    ALREADY_EXISTS: "ALREADY_EXISTS",
  },
  SERVER: {
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
  },
  VALIDATION: {
    INVALID_INPUT: "INVALID_INPUT",
    MISSING_FIELD: "MISSING_FIELD",
    MISSING_DEPENDENCY: "MISSING_DEPENDENCY",
  },
  REPOSITORY: {
    GENERIC: "REPOSITORY_ERROR",
    INVALID_SLUG: "REPOSITORY_INVALID_SLUG",
    NOT_FOUND: "REPOSITORY_NOT_FOUND",
  },
  GENERAL: {
    BAD_REQUEST: "BAD_REQUEST",
  },
};

export default ERROR_CODES;
